[game]
minecraft_path = ["/home/link/.minecraft"]
java_path = ["java"]

[download]
source = "Default"
parallel_amount = 64
verify_data = true
curseforge_api_key = "$2a$10$wuAJuNZuted3NORVmpgUC.m8sI.pv1tOPKZyBgLFGjxFp/br0lZCC"

[launch]
max_mem = 0
game_independent = true
recheck = true
jvm_args = ""
game_args = ""
window_title = ""
wrapper_path = ""
wrapper_args = ""

[appearance]
language = "zh-CN"
auto_check_update = true

[auth]
microsoft_client_id = "c36a9fb6-4f2a-41ff-90bd-ae7cc92031eb"

[[auth.accounts]]
type = "microsoft"
player_name = "fgfgui_link"
uuid = "2b751eba476e4c6da514e44eced51ab3"
xuid = ""
