import { Palette, StyleMetrics } from "std-widgets.slint";
export component FocusBorder inherits Rectangle {
    border-width: 2px;
    border-color: Palette.foreground;

    Rectangle {
        x: parent.border-width;
        y: parent.border-width;
        width: parent.width - 2 * parent.border-width;
        height: parent.height - 2 * parent.border-width;
        border-width: 1px;
        border-radius: parent.border-radius - 2px;
        border-color: Palette.background;
    }
}