import { Palette, StyleMetrics, Button, ScrollView } from "std-widgets.slint";
import { PageContainer } from "../base/page-container.slint";

export struct JavaItem {
    path: string,
    version: string,
    main-version: int,
    is-64bit: bool,
}

component JavaListItem inherits Rectangle {
    in property <string> badge-text;
    in property <string> title;
    in property <string> subtitle;
    in property <bool> is-64bit: false;
    in property <bool> is-action: false;
    in property <bool> default-active: false;

    callback clicked;

    height: root.is-action ? 50px : 68px;

    background: touch.has-hover || root.default-active ? Palette.alternate-background : transparent;

    touch := TouchArea {
        clicked => { root.clicked(); }
    }

    HorizontalLayout {
        padding-left: StyleMetrics.layout-padding;
        padding-right: StyleMetrics.layout-padding;
        spacing: StyleMetrics.layout-spacing;
        alignment: start;

        Rectangle {
            width: 32px;
            height: root.height;

            if (!root.is-action) : Rectangle {
                width: 100%;
                height: 100%;

                Text {
                    text: "☕";
                    font-size: 2rem;
                    vertical-alignment: center;
                    horizontal-alignment: center;
                }

                if (root.badge-text != "") : Rectangle {
                    background: Palette.foreground;
                    border-radius: 4px;
                    width: 22px;
                    height: 14px;
                    x: 16px;
                    y: 36px;

                    Text {
                        text: root.badge-text;
                        color: Palette.background;
                        font-size: 0.83rem;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }
            }

            if (root.is-action) : Rectangle {
                width: 26px;
                height: 26px;
                y: (parent.height - self.height) / 2;

                Rectangle { width: 100%; height: 4px; background: Palette.foreground; y: 11px; }
                Rectangle { width: 4px; height: 100%; background: Palette.foreground; x: 11px; }
            }
        }

        VerticalLayout {
            alignment: center;
            spacing: StyleMetrics.layout-spacing;

            HorizontalLayout {
                spacing: 6px;
                alignment: start;

                Text {
                    text: root.title;
                    font-size: 1.25rem;
                    color: Palette.foreground;
                }

                if (!root.is-action && root.is-64bit) : Rectangle {
                    background: Palette.accent-background;
                    border-radius: 3px;
                    width: 36px;
                    height: 16px;
                    y: (parent.height - self.height) / 2;

                    Text {
                        text: "64bit";
                        color: Palette.accent-foreground;
                        font-size: 0.75rem;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }
            }

            if (!root.is-action && root.subtitle != "") : Text {
                text: root.subtitle;
                font-size: 1.08rem;
                color: Palette.alternate-foreground;
            }
        }
    }
}

export component JavaChoosePage inherits PageContainer {
    width: 340px;
    height: 420px;
    content-padding-left: 0px;
    content-padding-right: 0px;

    in-out property <[JavaItem]> java-list: [];
    in-out property <int> selected-java-index: -1;
    in-out property <bool> is-searching: false;

    callback search-java();
    callback java-selected(index: int);
    callback add-java-path();

    ScrollView {
        VerticalLayout {
            spacing: 0px;

            for java-item[idx] in root.java-list : JavaListItem {
                badge-text: java-item.main-version > 0 ? "" + java-item.main-version + "+" : "";
                title: java-item.version;
                subtitle: java-item.path;
                is-64bit: java-item.is-64bit;
                default-active: idx == root.selected-java-index;
                clicked => {
                    root.selected-java-index = idx;
                    root.java-selected(idx);
                }
            }

            Rectangle { height: 12px; }

            JavaListItem {
                is-action: true;
                title: "添加新的 Java 运行时";
                clicked => { root.add-java-path(); }
            }

            JavaListItem {
                is-action: true;
                title: root.is-searching ? "正在搜索..." : "尝试搜索可用 Java 运行时";
                default-active: root.is-searching;
                clicked => { root.search-java(); }
            }
        }
    }
}
